#!/usr/bin/env python3
"""C1 real-prose streaming benchmark (throughput diagnostic).

Freeze-then-measure: the three prose prompts, sampling/template controls and
their corpus SHA are frozen to disk BEFORE any traffic. Each case then runs
--repeats (default 5) measured streaming requests plus --warmup (default 1)
separately-marked warmup requests.

Per-case cold start: when --flush-cold is passed AND the caller exports
QUAL_HARNESS_OWNER_ADMITTED=1, POST /flush_cache is sent before each case.
Without owner admission the flag is refused (fail closed). This client never
starts, stops or restarts any server and never interrupts other processes.

Rows: one complete JSON row per request (warmup rows marked) with
case/repeat/valid/finish_reason/usage/wall_s/ttft_s/e2erate and the raw
preserved events. A length-limited generation is recorded as INVALID
(finish_length) — it is a diagnostic datapoint, never a silent pass. The run
exits nonzero unless every measured row is valid.

Default thinking policy: chat_template_kwargs.enable_thinking=False
(throughput diagnostic). --thinking enables native thinking at low effort.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

from http_client import (  # noqa: E402
    MODEL_ID,
    ConcurrencyGate,
    OpenAICompatClient,
    row_validity,
    thinking_request_fields,
    build_chat_payload,
)
from benchmark_evidence import (
    bind_requests,
    input_hash,
    load_manifest,
    verify_bound_epoch,
)

# ---------------------------------------------------------------------------
# Frozen prose corpus (written before any traffic; sha256 in every run manifest)
# ---------------------------------------------------------------------------

PROSE_CASES: List[Dict[str, str]] = [
    {
        "case_id": "db_index_write_read",
        "prompt": (
            "You are advising a team that operates a high-write OLTP database. "
            "Explain in detail how a B+ tree secondary index changes the cost "
            "profile of a workload in which millions of small transactions "
            "update a hot subset of rows every minute. Cover the following "
            "points with concrete mechanics rather than generalities. First, "
            "describe how index maintenance amplifies writes: page reads for "
            "positioning, copy-on-write of leaf pages, dirty-page pressure in "
            "the buffer pool, and the extra WAL volume generated by index "
            "updates. Second, explain how read amplification is reduced: "
            "range scans that touch sequential leaf pages, covering indexes "
            "that avoid heap fetches, and the effect of fill factor on page "
            "splits. Third, compare this with an LSM-style engine under the "
            "same workload: memtable flushes, compaction backlog, write "
            "stalls, and how tombstones from updates interact with secondary "
            "indexes. Fourth, give a decision procedure: which monitoring "
            "signals such as WAL bytes per committed row, page split rate, "
            "compaction queue depth, and p99 read latency should the team "
            "watch, and what thresholds would push you to recommend dropping "
            "an index, adding a covering index, or switching storage "
            "engines. Conclude with a short, concrete recommendation for a "
            "payments ledger that is written constantly between 09:00 and "
            "17:00 and scanned for reconciliation once per night."
        ),
    },
    {
        "case_id": "city_heat_water",
        "prompt": (
            "A mid-sized city of two million people expects longer and hotter "
            "heat waves over the next decade. Its water utility must plan "
            "reservoir releases and pumping capacity. Explain in detail the "
            "causal chain from extreme heat to water demand. Start with how "
            "daytime and nighttime temperatures change residential "
            "consumption through evapotranspiration of gardens, higher "
            "shower and laundry frequency, and evaporative cooling. Then "
            "describe the pressure on the distribution network: peak-hour "
            "demand spikes, pipe leakage that rises with temperature "
            "differentials and ground movement, and the energy cost of "
            "pumping against higher afternoon loads. Next, analyze the "
            "supply side: reservoir evaporation rates, reduced snowpack and "
            "earlier melt shifting the seasonal curve, and competing "
            "withdrawals for agriculture and hydropower. Evaluate three "
            "mitigation portfolios and their tradeoffs: demand management "
            "through tiered pricing, leak repair, and public heat alerts; "
            "supply diversification through aquifer storage and recovery, "
            "reclaimed water for industry, and inter-basin transfers; and "
            "urban cooling through street trees, reflective roofs, and "
            "depaving, noting how each reduces heat and water stress "
            "together. Finish with a recommended sequencing of investments "
            "for a utility that has a fixed ten-year budget and must keep "
            "bills affordable for low-income households."
        ),
    },
    {
        "case_id": "compression_vs_random_access",
        "prompt": (
            "Explain in detail why columnar compression and fast random "
            "access pull in opposite directions in analytical storage "
            "engines. Begin with the mechanics that give compression its "
            "gains: run-length and dictionary encoding over sorted columns, "
            "bit packing of low-cardinality integers, and delta encoding for "
            "timestamps, noting how sorting a table by one column improves "
            "ratios on the remaining columns. Then explain what breaks when "
            "a query needs a single row: dictionaries must be paged in "
            "whole, delta chains must be replayed from a base value, and "
            "lightweight decompression of one value can force decompressing "
            "an entire page. Describe how real systems soften this tradeoff: "
            "page-level secondary indexes and zone maps that skip pages, "
            "small uncompressed row caches or hybrid transactional stores "
            "for point lookups, and adaptive encodings chosen per column "
            "from sampled data. Analyze the cost model an administrator "
            "should use: bytes saved per column versus CPU cycles spent "
            "decompressing under a scan-heavy versus point-heavy trace, and "
            "how that balance shifts on NVMe where random reads are cheap "
            "but still not free. Conclude with guidance for a clickstream "
            "analytics table that mostly serves aggregated dashboards but "
            "must occasionally fetch the raw events of one user session for "
            "a support investigation."
        ),
    },
]

MAX_TOKENS = 2048
TEMPERATURE = 0.0
TOP_P = 1.0
DEFAULT_REPEATS = 5
DEFAULT_WARMUP = 1
MIN_MEANINGFUL_CHARS = 200  # a meaningful prose answer, not a stub


def prose_payloads(thinking=None):
    thinking = thinking if thinking is not None else thinking_request_fields(False)
    return {
        case["case_id"]: build_chat_payload(
            [{"role": "user", "content": case["prompt"]}],
            model=MODEL_ID,
            max_tokens=MAX_TOKENS,
            temperature=TEMPERATURE,
            top_p=TOP_P,
            thinking=thinking,
        )
        for case in PROSE_CASES
    }


def corpus_sha256() -> str:
    """Stable SHA over the frozen corpus (case_id + prompt pairs)."""
    canon = json.dumps(
        sorted([[c["case_id"], c["prompt"]] for c in PROSE_CASES]),
        ensure_ascii=False,
        sort_keys=True,
    )
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()


def write_corpus_lock(
    path: Path, *, base: str, thinking: Dict[str, Any], repeats: int, warmup: int
) -> None:
    if path.exists():
        raise SystemExit(f"refusing to overwrite corpus lock: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    lock = {
        "kind": "qualification-c1-corpus-lock",
        "model_id": MODEL_ID,
        "base": base,
        "corpus_sha256": corpus_sha256(),
        "input_sha256": {
            key: input_hash(payload)
            for key, payload in prose_payloads(thinking).items()
        },
        "requests": prose_payloads(thinking),
        "cases": [
            {
                "case_id": c["case_id"],
                "prompt_sha256": hashlib.sha256(
                    c["prompt"].encode("utf-8")
                ).hexdigest(),
            }
            for c in PROSE_CASES
        ],
        "sampling": {
            "max_tokens": MAX_TOKENS,
            "temperature": TEMPERATURE,
            "top_p": TOP_P,
            "repeats": repeats,
            "warmup": warmup,
            "thinking": thinking,
        },
        "frozen_before_traffic_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(lock, indent=2) + "\n")
    os.replace(tmp, path)  # atomic freeze


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


def run_bench(
    base: str,
    out_path: Path,
    *,
    repeats: int = DEFAULT_REPEATS,
    warmup: int = DEFAULT_WARMUP,
    thinking: Optional[Dict[str, Any]] = None,
    timeout_s: float = 900.0,
    flush_cold: bool = False,
    variant: str = "",
    promotion_manifest=None,
) -> Dict[str, Any]:
    if flush_cold and os.environ.get("QUAL_HARNESS_OWNER_ADMITTED") != "1":
        raise SystemExit(
            "--flush-cold requires QUAL_HARNESS_OWNER_ADMITTED=1: only the "
            "owner-admitted idle campaign endpoint may be flushed"
        )
    if type(repeats) is not int or repeats < 1 or type(warmup) is not int or warmup < 0:
        raise ValueError("repeats must be positive and warmup nonnegative integers")
    raw_path = out_path.with_suffix(out_path.suffix + ".raw.jsonl")
    corpus_path = out_path.with_suffix(out_path.suffix + ".corpus.json")
    if any(path.exists() for path in (out_path, raw_path, corpus_path)):
        raise FileExistsError("prose output and sidecars must all be fresh")
    if promotion_manifest is not None and "runtime_context" in promotion_manifest:
        if repeats != 5 or warmup != 1 or flush_cold:
            raise ValueError(
                "bound prose requires five repeats, one warmup, and warm-prefix policy"
            )
    thinking = thinking if thinking is not None else thinking_request_fields(False)
    requests = json.loads(json.dumps(prose_payloads(thinking)))
    bindings = bind_requests(promotion_manifest, "prose", requests)
    verify_bound_epoch(promotion_manifest, base)
    write_corpus_lock(
        corpus_path, base=base, thinking=thinking, repeats=repeats, warmup=warmup
    )
    gate = ConcurrencyGate(1)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(out_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    raw_fd = os.open(raw_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    flush_log: List[Dict[str, Any]] = []
    measured: List[Dict[str, Any]] = []
    warm_rows = 0

    def emit_raw(case, repeat, res, warm):
        row = {
            "case": case,
            "repeat": repeat,
            "warmup": warm,
            "model": MODEL_ID,
            "model_reported": res.model_reported,
            "request": requests[case],
            "input_sha256": input_hash(requests[case]),
            "usage": res.usage,
            "finish_reason": res.finish_reason,
            "error": res.error,
            "content": res.content or "",
            "raw_events": res.raw_events,
        }
        os.write(raw_fd, (json.dumps(row, ensure_ascii=False) + "\n").encode())
        os.fsync(raw_fd)

    def emit(row: Dict[str, Any]) -> None:
        row["input_sha256"] = input_hash(requests[row["case"]])
        if bindings and not row["warmup"]:
            row["_evidence"] = bindings[row["case"]]
        line = (json.dumps(row, ensure_ascii=False) + "\n").encode("utf-8")
        os.write(fd, line)  # single append write per row
        os.fsync(fd)

    try:
        client = OpenAICompatClient(base)
        client.verify_model()
        for case in PROSE_CASES:
            if flush_cold:
                verify_bound_epoch(promotion_manifest, base)
                status, body = client.flush_cache(admitted=True, timeout=30.0)
                flush_log.append(
                    {
                        "case": case["case_id"],
                        "status": status,
                        "body": body[:200],
                        "ts_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    }
                )
                if status != 200:
                    raise SystemExit(
                        f"flush_cache failed for {case['case_id']}: HTTP {status}"
                    )
            request = requests[case["case_id"]]
            messages = request["messages"]
            controls = {
                key: request[key]
                for key in ("chat_template_kwargs", "reasoning_effort")
                if key in request
            }
            for w in range(warmup):  # separately marked warmup, never measured
                verify_bound_epoch(promotion_manifest, base)
                with gate.slot():
                    res = client.chat_stream(
                        messages,
                        max_tokens=request["max_tokens"],
                        temperature=request["temperature"],
                        top_p=request["top_p"],
                        thinking=controls,
                        timeout=timeout_s,
                    )
                emit_raw(case["case_id"], w, res, True)
                warm_rows += 1
                emit(
                    {
                        "case": case["case_id"],
                        "repeat": "warmup",
                        "warmup": True,
                        "valid": False,
                        "reason": "warmup_not_measured",
                        "ok": res.ok,
                        "error": res.error,
                        "finish_reason": res.finish_reason,
                        "usage": res.usage,
                        "wall_s": res.wall_s,
                        "ttft_s": res.ttft_s,
                        "e2erate": res.e2e_output_tok_per_s,
                        "model": MODEL_ID,
                        "variant": variant,
                        "ts_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                        "final_text": (res.content or "")[-1000:],
                        "raw_events": res.raw_events,
                    }
                )
            for rep in range(repeats):
                verify_bound_epoch(promotion_manifest, base)
                with gate.slot():  # admission strictly precedes the clock
                    res = client.chat_stream(
                        messages,
                        max_tokens=request["max_tokens"],
                        temperature=request["temperature"],
                        top_p=request["top_p"],
                        thinking=controls,
                        timeout=timeout_s,
                    )
                emit_raw(case["case_id"], rep, res, False)
                epoch_verified = verify_bound_epoch(promotion_manifest, base)
                valid, reason = row_validity(
                    res,
                    require_finish="stop",
                    require_content=True,
                    min_content_chars=MIN_MEANINGFUL_CHARS,
                )
                if res.model_reported != MODEL_ID:
                    valid, reason = False, "wrong_reported_model"
                row = {
                    "case": case["case_id"],
                    "repeat": rep,
                    "warmup": False,
                    "model_reported": res.model_reported,
                    "epoch_verified": epoch_verified,
                    "valid": valid,
                    "reason": reason,
                    "ok": res.ok,
                    "error": res.error,
                    "finish_reason": res.finish_reason,
                    "usage": res.usage,
                    "wall_s": res.wall_s,
                    "ttft_s": res.ttft_s,
                    "e2erate": res.e2e_output_tok_per_s,
                    "first_fragment_kind": res.first_fragment_kind,
                    "model": MODEL_ID,
                    "variant": variant,
                    "ts_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "final_text": (res.content or "")[-4000:],
                    "raw_events": res.raw_events,
                }
                measured.append(row)
                emit(row)
    finally:
        os.close(fd)
        os.close(raw_fd)

    invalid = [r for r in measured if not r["valid"]]
    summary = {
        "kind": "qualification-c1-prose-summary",
        "promotion_bound": bool(bindings),
        "scope": "PROSE_DIAGNOSTIC" if not bindings else "BOUND_PROSE_LANE",
        "model_id": MODEL_ID,
        "corpus_sha256": corpus_sha256(),
        "cases": [c["case_id"] for c in PROSE_CASES],
        "repeats": repeats,
        "warmup": warmup,
        "warm_rows": warm_rows,
        "measured_rows": len(measured),
        "invalid_rows": [
            {"case": r["case"], "repeat": r["repeat"], "reason": r["reason"]}
            for r in invalid
        ],
        "flush_log": flush_log,
        "median_e2erate_by_case": {
            c["case_id"]: _median(
                [
                    r["e2erate"]
                    for r in measured
                    if r["case"] == c["case_id"] and r["e2erate"] is not None
                ]
            )
            for c in PROSE_CASES
        },
        "ok": len(measured) == repeats * len(PROSE_CASES) and not invalid,
    }
    summary_path = out_path.with_suffix(out_path.suffix + ".summary.json")
    tmp = summary_path.with_suffix(summary_path.suffix + ".tmp")
    tmp.write_text(json.dumps(summary, indent=2) + "\n")
    os.replace(tmp, summary_path)
    return summary


def _median(xs: List[float]) -> Optional[float]:
    if not xs:
        return None
    s = sorted(xs)
    n = len(s)
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description="C1 real-prose streaming benchmark")
    p.add_argument("--base", required=True, help="explicit endpoint base URL")
    p.add_argument(
        "--output", required=True, help="JSONL rows (exclusive, no rerun overwrite)"
    )
    p.add_argument("--repeats", type=int, default=DEFAULT_REPEATS)
    p.add_argument("--warmup", type=int, default=DEFAULT_WARMUP)
    p.add_argument("--timeout", type=float, default=900.0)
    p.add_argument(
        "--thinking",
        action="store_true",
        help="enable native thinking at low effort (default: enable_thinking=False)",
    )
    p.add_argument(
        "--flush-cold",
        action="store_true",
        help="POST /flush_cache before each case (requires owner admission env)",
    )
    p.add_argument("--variant", default="", help="optional label (e.g. AR / NEXTN)")
    p.add_argument(
        "--promotion-manifest",
        help="frozen common manifest; absent means diagnostic-only",
    )
    args = p.parse_args(argv)

    out = Path(args.output)
    if out.exists():
        print(f"refusing to overwrite existing output: {out}", file=sys.stderr)
        return 2
    thinking = (
        thinking_request_fields(True, "low")
        if args.thinking
        else thinking_request_fields(False)
    )
    summary = run_bench(
        args.base,
        out,
        repeats=args.repeats,
        warmup=args.warmup,
        thinking=thinking,
        timeout_s=args.timeout,
        flush_cold=args.flush_cold,
        variant=args.variant,
        promotion_manifest=load_manifest(args.promotion_manifest),
    )
    print(json.dumps(summary, indent=2))
    return 0 if summary["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
